# -*- coding: utf-8 -*-
"""Untitled33.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19onoZNLwPlFgzreTpHBknXfLNOwGg3NY
"""

import random
letters = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']
numbers = ['0','1','2','3','4','5','6','7','8','9']
symbols = ['!','@','#','$','%','&','^','(',")","{","}","*","+"]
letter_input = int(input("How many letters you want in your password = "))
number_input = int(input("How many numbers you want in your password = "))
symbol_input = int(input("How many symbols you want in your password = "))
password = []
for char in range(1,letter_input+1):
  char = random.choice(letters)
  password+=char
for char in range(1,number_input+1):
  char = random.choice(numbers)
  password+=char
for char in range(1,symbol_input+1):
  char = random.choice(symbols)
  password+=char
random.shuffle(password)
strong_password = ""
for char in password:
  strong_password+=char
print("The Strong Password is = ",strong_password)